
package webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JcqWebService", targetNamespace = "http://ghroth251.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JcqWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "linkSocket", targetNamespace = "http://ghroth251.com/", className = "webService.client.LinkSocket")
    @ResponseWrapper(localName = "linkSocketResponse", targetNamespace = "http://ghroth251.com/", className = "webService.client.LinkSocketResponse")
    @Action(input = "http://ghroth251.com/JcqWebService/linkSocketRequest", output = "http://ghroth251.com/JcqWebService/linkSocketResponse")
    public String linkSocket(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataByComder", targetNamespace = "http://ghroth251.com/", className = "webService.client.GetDataByComder")
    @ResponseWrapper(localName = "getDataByComderResponse", targetNamespace = "http://ghroth251.com/", className = "webService.client.GetDataByComderResponse")
    @Action(input = "http://ghroth251.com/JcqWebService/getDataByComderRequest", output = "http://ghroth251.com/JcqWebService/getDataByComderResponse")
    public String getDataByComder(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendJcqMsg", targetNamespace = "http://ghroth251.com/", className = "webService.client.SendJcqMsg")
    @ResponseWrapper(localName = "sendJcqMsgResponse", targetNamespace = "http://ghroth251.com/", className = "webService.client.SendJcqMsgResponse")
    @Action(input = "http://ghroth251.com/JcqWebService/sendJcqMsgRequest", output = "http://ghroth251.com/JcqWebService/sendJcqMsgResponse")
    public String sendJcqMsg(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
